jsphp:
    resource: "@JSPHPBundle/Controller/"
    type:     annotation
    prefix:   /

jsphp_secured:
    resource: "@JSPHPBundle/Controller/AdminController.php"
    type:     annotation

JSPHPBundle:
    resource: "@JSPHPBundle/Resources/config/routing.yml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
