<?php

namespace JSPHP\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FunctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunctRepository extends EntityRepository
{
}
